global:
  image:
    registry: ""
    tag: ""
  store:
    consensus:
      name: ""
      image:
        registry: ""
        tag: ""
  openpolicyagent:
    enabled: false
    image:
      registry: ""
      tag: ""

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: onosproject/grpc-client
  tag: v0.0.0
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

store:
  consensus:
    enabled: true
    name: ""
    image:
      registry: ""
      repository: atomix/atomix-raft-storage-node
      tag: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    clusters: 1
    replicas: 1
    partitions: 1
    raft: {}
    persistence:
      storageClass: ""
      storageSize: 1Gi

service:
  type: ClusterIP

ports:
  grpc:
    insecure: 4040

nodeSelector: {}

tolerations: []

affinity: {}
