apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ template "monitor-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  resourceNames:
  - {{ template "monitor-service.fullname" . }}-test
  - monitor-config
  verbs:
  - '*'