apiVersion: v2
name: open-cnc
description: Helm chart deploying Open-CNC
kubeVersion: ">=1.17.0"
type: application
version: 1.2.27
appVersion: v1.1.0
maintainers:
  - name: Fredrik Hallström
dependencies:
  - name: main-service
    condition: import.main-service.enabled
    repository: file://../main-service
    version: 0.0.1
  - name: tsn-service
    condition: import.tsn-service.enabled
    repository: file://../tsn-service
    version: 0.0.1
  - name: monitor-service
    condition: import.monitor-service.enabled
    repository: file://../monitor-service
    version: 0.0.0
  - name: grpc-client
    condition: import.grpc-client.enabled
    repository: file://../grpc-client
    version: 0.0.0
