apiVersion: config.onosproject.org/v1beta1
kind: Model
metadata:
  name: {{ template "tsn-model.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tsn-model.labels" . | nindent 4 }}
spec:
  plugin:
    type: tsn-model
    version: {{ .Chart.AppVersion | quote }}
  modules:
  - name: ieee802-dot1ab-lldp
    organization: Ericsson AB
    revision: 2018-11-13
    file: ieee802-dot1ab-lldp.yang
  - name: ieee802-dot1q-bridge
    organization: IEEE 802.1 Working Group
    revision: 2018-03-07
    file: ieee802-dot1q-bridge.yang
  - name: ieee802-dot1q-fqtss
    organization: IEEE 802.1 Working Group
    revision: 2014-12-15
    file: ieee802-dot1q-fqtss.yang
  - name: ieee8021-mstp
    organization: IEEE 802.1 Working Group
    revision: 2012-08-11
    file: ieee8021-mstp.yang
  - name: ietf-interfaces
    organization: IETF NETMOD (Network Modeling) Working Group
    revision: 2018-02-20
    file: ietf-interfaces.yang
  - name: ietf-keystore
    organization: IETF NETCONF (Network Configuration) Working Group
    revision: 2016-10-31
    file: ietf-keystore.yang
  - name: ietf-netconf
    organization: IETF NETCONF (Network Configuration) Working Group
    revision: 2011-06-01
    file: ietf-netconf@2011-06-01.yang
  - name: ietf-netconf-acm
    organization: IETF NETCONF (Network Configuration) Working Group
    revision: 2018-02-14
    file: ietf-netconf-acm@2018-02-14.yang
  - name: ietf-ptp
    organization: Ericsson AB
    revision: 2011-06-01
    file: ietf-ptp.yang
  - name: ietf-routing
    organization: Ericsson AB
    revision: 2018-02-14
    file: ietf-routing.yang
  - name: ietf-system
    organization: Ericsson AB
    revision: 2018-02-14
    file: ietf-system.yang
  - name: ietf-yang-library
    organization: Ericsson AB
    revision: 2018-02-14
    file: ietf-yang-library.yang
  - name: nc-notifications
    organization: Ericsson AB
    revision: 2018-02-14
    file: nc-notifications.yang
  - name: sysrepo-module-dependencies
    organization: Ericsson AB
    revision: 2018-02-14
    file: sysrepo-module-dependencies.yang
  - name: sysrepo-module-versions
    organization: Ericsson AB
    revision: 2011-06-01
    file: sysrepo-module-versions.yang
  - name: sysrepo-notification-store
    organization: Ericsson AB
    revision: 2018-02-14
    file: sysrepo-notification-store.yang
  - name: sysrepo-persistent-data
    organization: Ericsson AB
    revision: 2011-06-01
    file: sysrepo-persistent-data.yang
  - name: notifications
    organization: IETF NETCONF WG
    revision: 2008-07-14
    file: notifications.yang
  - name: ietf-netconf-server
    organization: IETF NETCONF (Network Configuration) Working Group
    revision: 2016-11-02
    file: ietf-netconf-server.yang
  - name: ietf-netconf-notifications
    organization: IETF NETCONF (Network Configuration) Working Group
    revision: 2012-02-06
    file: ietf-netconf-notifications.yang
  - name: ietf-netconf-monitoring
    organization: IETF NETCONF (Network Configuration) Working Group
    revision: 2010-10-04
    file: ietf-netconf-monitoring.yang
  files:
    {{- range $path, $_  := $.Files.Glob "files/yang/*.yang" }}
    {{ base $path }}: |
{{ $.Files.Get $path | indent 6 }}
    {{- end }}